// Builds offline/poker-night.html: the whole game in one self-contained HTML file
// (you against bots, progress saved in the browser). No server needed, so it can be
// opened straight from disk or inside apps that preview HTML.
//
//   npm run build:offline
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const OUT = path.join(root, 'offline', 'poker-night.html');

function replaceOnce(text, find, replacement) {
  if (!text.includes(find)) throw new Error(`build-offline: could not find ${JSON.stringify(find.slice(0, 60))}`);
  return text.replace(find, () => replacement);
}

function build() {
  const font = fs.readFileSync(path.join(root, 'public/fonts/black-ops-one.woff2')).toString('base64');
  const css = replaceOnce(read('public/style.css'), 'url("fonts/black-ops-one.woff2")', `url("data:font/woff2;base64,${font}")`);

  // server modules, wrapped for the in-page loader (offline/runtime.js)
  const mod = (name, file) =>
    `__define(${JSON.stringify(name)}, function (module, exports, require, process, __dirname, Buffer) {\n${read(file)}\n});`;
  const scripts = [
    read('offline/runtime.js'),
    mod('hand', 'src/hand.js'),
    mod('table', 'src/table.js'),
    mod('sandbox', 'src/sandbox.js'),
    mod('db', 'src/db.js'),
    read('offline/local-server.js'),
    read('public/effects.js'),
    read('public/app.js'),
  ];
  for (const s of scripts) {
    if (/<\/script/i.test(s)) throw new Error('build-offline: a script contains "</script"');
  }

  let html = read('public/index.html');
  html = replaceOnce(html, '<title>Poker Night</title>', '<title>Poker Night (offline)</title>');
  html = replaceOnce(html, '  <link rel="preload" href="fonts/black-ops-one.woff2" as="font" type="font/woff2" crossorigin>\n', '');
  html = replaceOnce(html, '<link rel="stylesheet" href="style.css">', `<style>\n${css}\n</style>`);
  html = replaceOnce(
    html,
    '  <script src="/socket.io/socket.io.js"></script>\n  <script src="effects.js"></script>\n  <script src="app.js"></script>',
    scripts.map((s) => `<script>\n${s}\n</script>`).join('\n'),
  );
  return `<!-- Poker Night, offline edition. Generated by scripts/build-offline.js; edit the sources, not this file. -->\n${html}`;
}

if (require.main === module) {
  const html = build();
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, html);
  console.log(`Wrote ${path.relative(root, OUT)} (${Math.round(html.length / 1024)} KB)`);
}

module.exports = { build, OUT };
